# API calls: Create, Retrieve, Update, Delete becomes POST, GET, PUT, and DELETE
# npm install nodemon -g --save --auto compile

# node server.js
# nodemon server.js -- to execute the project

# npm run start -> for the Dev Environment
# npm run dev -> for the Dev Environment


# node server.js & -> server
# service nginx start 

# --stop service------------
# top 
# kill 111
# or 
# killall node

# npm i --dev
# require('crypto').randomBytes(64).toString('hex')




# GetAll


# GET http://192.168.123.199:6001/products 
# GET http://83.136.219.132:6001/items

//GET http://localhost:6001/items/test


//GET http://localhost:6001/users/register


# POST http://localhost:6004/users/register
# Content-Type: application/json

# {
#   "userName": "usr003",
#   "password": "123"
# }


//Request Initial token
###
POST http://localhost:6000/users/login
Content-Type: application/json

{
  "userName": "usr003",
  "password": "123"
}

//Request for new token (send the refresh token to get a new access token)
###
POST http://localhost:6000/users/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNyMDAzIiwiaWF0IjoxNjEyNDMxMzkwfQ.14OiFpgNe7OMZdSab86cJKrrDL03GqlRxDx-vYjv_rg"
}

// Access the content
###
GET http://localhost:6000/users/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNyMDAzIiwiaWF0IjoxNjEyNDMyMzk2LCJleHAiOjE2MTI0MzI0NTF9.EpzxsdidM_VxEG2hyK3e7PCei5qjqRGzUlwpTrssh0o








