# API calls: Create, Retrieve, Update, Delete becomes POST, GET, PUT, and DELETE
# npm install nodemon -g --save --auto compile

# npm run start -> for the Dev Environment
# npm run dev -> for the Dev Environment

# node server.js
# nodemon server.js -- to execute the project


# node server.js & -> server
# service nginx start 

# --stop service------------
# top 
# kill 111
# or 
# killall node

# npm i --dev
# require('crypto').randomBytes(64).toString('hex')




# GetAll


# GET http://192.168.123.199:6001/products 
# GET http://83.136.219.132:6001/items

//GET http://localhost:6001/items/test


//GET http://localhost:6001/users/register


POST http://localhost:6000/users/register
Content-Type: application/json

{
  "userName": "usr004",
  "password": "123"
}


//Request Initial token
###
POST http://localhost:6000/login
Content-Type: application/json

{
  "userName": "usr003",
  "password": "123"
}


// Access the content
###
GET http://localhost:6000/users/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNyMDAzIiwiaWF0IjoxNjEyNDQ1Nzc3LCJleHAiOjE2MTI0NDU4MzJ9.N8qJmOSJHrsNeflIMz4qUG_-dtP5n0RkviKTXqM1BeQ



//Request for new token (send the refresh token to get a new access token)
###
POST http://localhost:6000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNyMDAzIiwiaWF0IjoxNjEyNDQyNzAxfQ.P5vG_uVlZqnx6t21p5IDcAWyAHk9NJOSkl-8PYO5Neo"
}


//Delete the refresh token from the server
###
DELETE http://localhost:6000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNyMDAzIiwiaWF0IjoxNjEyNDQyNzAxfQ.P5vG_uVlZqnx6t21p5IDcAWyAHk9NJOSkl-8PYO5Neo"
}






