# API calls: Create, Retrieve, Update, Delete becomes POST, GET, PUT, and DELETE
# npm install nodemon -g --save --auto compile

# node server.js
# nodemon server.js -- to execute the project

# npm run start -> for the Dev Environment
# npm run dev -> for the Dev Environment


# node server.js & -> server
# service nginx start 

# --stop service------------
# top 
# kill 111
# or 
# killall node


# GetAll


# GET http://192.168.123.199:6001/products 
# GET http://83.136.219.132:6001/items

//GET http://localhost:6001/items/test


//GET http://localhost:6001/users/register


# POST http://localhost:6004/users/register
# Content-Type: application/json

# {
#   "userName": "usr003",
#   "password": "123"
# }


POST http://localhost:6004/users/login
Content-Type: application/json

{
  "userName": "usr003",
  "password": "123"
}



# GET http://localhost:6004/users/1








