# API calls: Create, Retrieve, Update, Delete becomes POST, GET, PUT, and DELETE
# npm install nodemon -g --save --auto compile

# node server.js
# nodemon server.js -- to execute the project

# node server.js & -> server
# service nginx start 

# --stop service------------
# top 
# kill 111
# or 
# killall node


# GetAll


# GET http://192.168.123.199:6001/products 
GET http://83.136.219.132:6001/items



